### ISSUE TITLE
Why here needs "hypo_ids = topk_positions / vocab_size"

### ISSUE THREAD

**Issue by yz1019117968** [Tbabm/CUP#1]
https://github.com/Tbabm/CUP/blob/43ebf64c5d87ad205ded281dfec51c6b9d3052c9/models/beam.py#L91

I'm afraid that the above code causes the following line error.
https://github.com/Tbabm/CUP/blob/43ebf64c5d87ad205ded281dfec51c6b9d3052c9/models/beam.py#L122
```
The error log is shown here:
Traceback (most recent call last):
  File "infer.py", line 100, in <module>
    main()
  File "infer.py", line 96, in main
    infer(args)
  File "infer.py", line 91, in infer
    infer_instance.infer()
  File "infer.py", line 65, in infer
    hypos = self.beam_search(test_set)
  File "infer.py", line 55, in beam_search
    example_hypos = self._model.beam_search(example, self.beam_size, self.max_dec_step, BeamClass)
  File "D:\Projects\CommentUpdate_cup\models\updater.py", line 175, in beam_search
    hypos = self.nl_decoder.beam_search(example, beam_size, max_dec_step, BeamClass, **decoder_kwargs)
  File "D:\Projects\CommentUpdate_cup\models\decoder.py", line 273, in beam_search
    state_tm1 = beam.step(words_log_prob, state_tm1)
  File "D:\Projects\CommentUpdate_cup\models\beam.py", line 122, in step
    new_hypo_sents.append(self.live_hypo_sents[hypo_id] + [word_id])
TypeError: list indices must be integers or slices, not float
```

**Comment by Tbabm** [comment]
Sorry that I don't have enough time to dig into this issue for now. I can only provide some hints:
https://github.com/Tbabm/CUP/blob/43ebf64c5d87ad205ded281dfec51c6b9d3052c9/models/beam.py#L89-L93

Line 90: The top-k candidates are selected from the **whole** `scores` by flattening `scores`。Since there are more than one hypotheses, some candidates may be generated from different hypotheses. (A hypothesis refers to a sequence of tokens that was generated before this time step).
Line 91: Given a candidate, its hypo_id refers to the id of the hypothesis from which this candidate is generated.

I hope this can provide some help.

I would appreciate it if you could provide a way to replicate this error.

**Comment by yz1019117968** [comment]
Thanks for your kind reply. I changed the "/" to "//", then the program can run in normal. The latter operator can divide and return the integer value of the quotient, thereby obtaining the  "hypo_ids".
